name: CI/CD

on:
  push:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: frontend/dist

  test-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies and run frontend tests
        run: |
          cd frontend
          npm ci
          npm run test

  build-docker-images:
    runs-on: ubuntu-latest
    needs: test-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker images
        run: |
          docker build ./frontend/. -t euchre-frontend
          docker build ./backend/. -t euchre-backend
    services:
      docker:
        image: docker:stable-dind
